name: oidc-poc
on:
  pull_request:
    branches:
      - "develop"
jobs:
  auth:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Get id token
        run: |
          ID_TOKEN=$(curl -sLS -H "User-Agent: actions/oidc-client" -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
          "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=jfrog-github" | jq .value | tr -d '"')
          echo "ID_TOKEN=${ID_TOKEN}" >> $GITHUB_ENV
          echo "$ID_TOKEN"
      - name: Exchange token with access
        env:
          ID_TOKEN: ${{env.ID_TOKEN}}
          JFROG_PLATFORM_URL: https://hts2.jfrog.io
        run: |
          ACCESS_TOKEN=$(curl -XPOST -H "Content-Type: application/json" "https://hts2.jfrog.io/access/api/v1/oidc/token" -d "{\"grant_type\": \"urn:ietf:params:oauth:grant-type:token-exchange\", \"subject_token_type\":\"urn:ietf:params:oauth:token-type:id_token\", \"subject_token\": \"${ID_TOKEN}\", \"provider_name\": \"github\"}" | jq .access_token | tr -d '"')
          echo "ACCESS_TOKEN=${ACCESS_TOKEN}" >> $GITHUB_ENV
      - name: list token
        env:
          OIDC_AUDIENCE: "jfrog-github"
          OIDC_PROVIDER: "github"
        run: |
          RESPONSE=$(curl -s -o response.json -w "%{http_code}" -X POST -H "Content-type: application/json" https://hts2.jfrog.io/access/api/v1/oidc/token -d \
          "{\"grant_type\": \"urn:ietf:params:oauth:grant-type:token-exchange\",\"subject_token_type\":\"urn:ietf:params:oauth:token-type:id_token\",\"subject_token\": \"${{ env.ID_TOKEN }}\",\"provider_name\": \"${{ env.OIDC_PROVIDER }}\"}")
          echo "API Response:"
          echo "$RESPONSE"
          # Fetch file using the OIDC generated token
      - name: Fetch file using the OIDC generated token
        run: |
          curl -H "Authorization: Bearer $RESPONSE" -X GET https://hts2.jfrog.io/artifactory/api/storage/azure-pypi-cache/click/8.1.7/click-8.1.7-py3-none-any.whl
