name: "JFrog-GitHub NPM Publish OIDC Integration"
on: push

# This is required as per
# https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-cloud-providers#adding-permissions-settings
permissions:
  id-token: write

jobs:
  build:
     runs-on: ubuntu-latest
     env:
      OIDC_AUDIENCE: 'manu-audi'
      OIDC_PROVIDER: 'manu-oidc'
      PLATFORM_REPO: 'manu-npm-virtual'
     steps:
       - name: Setup JFrog cli / handshake via OIDC, with user
         uses: jfrog/setup-jfrog-cli@v4
         env:  
           JF_URL: https://incloudmaster.jfrog.io
         with:
           oidc-provider-name: ${{ env.OIDC_PROVIDER }}
           oidc-audience: ${{ env.OIDC_AUDIENCE }}
       - name: Print env
         run: printenv

       - name: Ping Artifactory
         run: jf rt ping       
           
       - name: Get npm auth token
         run: jf rt curl /artifactory/api/npm/auth > auth
             
       - name: npm registry
         run: |
          jf npm-config --repo-resolve=manu-npm-virtual --repo-deploy=manu-npm-virtual
       - name: npm install
         run: |
          jf npm install @extjs --loglevel verbose 
