name: "jfrog-oidc-test"


on:
  push:
    branches:
      - feature/jfrog-oidc


permissions:
  id-token: write
    
jobs:
  npm-publish-setup:
    runs-on: ubuntu-latest


    steps:
      
    - name: "Setup JFrog cli / handshake via OIDC, with user"
      uses: jfrog/setup-jfrog-cli@v4
      env:
        JF_URL: https://hts2.jfrog.io
      with:
        oidc-provider-name: github-oidc 
        oidc-audience: jfrog-github


    - name: Ping Artifactory
      run: jf rt ping


    - name: Get npm auth token
      run: jf rt curl /api/npm/auth > auth


    - name: Create .npmrc file
      run: |
        echo "loglevel=http" > .npmrc
        echo "fund=false" >> .npmrc
        echo "@mtg:registry=https://hts2.jfrog.io/artifactory/api/npm/manu-npm-virtual/" > .npmrc
        cat auth | sed "s/^_auth\(.*\)$/\/\/hts2.jfrog.io\/:_auth\1/"  | sed 's/ //g' >> .npmrc
    
    - name: npm install
      run: npm install @mtg/metrics-emitter --loglevel verbose
